name = "CubedSphereAquaplanet"
uuid = "20120c9c-789a-48f3-b192-7cd98bfd7960"
authors = ["Siddhartha Bishnu"]
version = "1.0.0-DEV"

[deps]
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
