name = "CubedSphereAquaplanet"
uuid = "d4f70586-8ff7-409e-805c-51002cc2bb24"
authors = ["Sid Bishnu"]
version = "1.0.0-DEV"

[deps]
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"

[compat]
Oceananigans = "0.97.7"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
